/**
 *  'BookId': 1006853204,
    'BookName': '文化入侵异世界',
    'AuthorId': 3112022,
    'Author': '姐姐的新娘',
    'IsVip': 1,
    'ImageStatus': 1,
    'LastUpdateChapterID': 376292828,
    'LastUpdateChapterName': '第三百零一章 过时',
    'LastChapterUpdateTime': 1506786023000,
    'LastVipUpdateChapterId': 387124661,
    'LastVipUpdateChapterName': '第三百零一章 过时',
    'LastVipChapterUpdateTime': 1506786023000,
    'WordsCount': 682009,
    'CategoryName': '科幻',
    'subCategoryName': '时空穿梭',
    'CategoryId': 100117,
    'BookStatus': '连载',
    'EnableBookUnitBuy': 0,
    'EnableBookUnitLease': 0,
    'BssReadTotal': 685864,
    'BssRecomTotal': 152538,
    'Label': '明星|种田文|赚钱',
    'Description': '一群巨龙搬着小板凳日夜追看《权力游戏》。精灵大德鲁伊们因为《忠犬八公的故事》而潸然泪下。人类与矮人在《炉石传说》酒馆中为一张传说卡牌而大大出手。甚至就连神明也亲',
    'ReadingType': 5,
    'AlgInfo': '',
    'Adid': 0,
    'overrating': null,
    'SourceType': 0,
    'SourceDesc': null,
    'AuthorTagId': '明星|种田文|赚钱',
    'BookInternalId': 5841993,
    'prob': 0,
    'recommendRate': null,
    'staticscore1': 5423
 */
import { Mock } from 'react-native-fetch-mock';

export default {
  '/api/v1/books': ({ method, url, params, urlparams, headers }) => {
    const all = Mock.mock({
      'list|2': [{
        'bookId|+1': 1006853204,
        'bookName': '文化入侵异世界',
        'authorId': 3112022,
        'author': '姐姐的新娘',
        'isVip': 1,
        'imageStatus': 1,
        'lastUpdateChapterID': 376292828,
        'lastUpdateChapterName': '第三百零一章 过时',
        'lastChapterUpdateTime': 1506786023000,
        'lastVipUpdateChapterId': 387124661,
        'lastVipUpdateChapterName': '第三百零一章 过时',
        'lastVipChapterUpdateTime': 1506786023000,
        'wordsCount': 682009,
        'categoryName': '科幻',
        'subCategoryName': '时空穿梭',
        'categoryId': 100117,
        'bookStatus': '连载',
        'enableBookUnitBuy': 0,
        'enableBookUnitLease': 0,
        'bssReadTotal': 685864,
        'bssRecomTotal': 152538,
        'label': '明星|种田文|赚钱',
        'description': '一群巨龙搬着小板凳日夜追看《权力游戏》。精灵大德鲁伊们因为《忠犬八公的故事》而潸然泪下。人类与矮人在《炉石传说》酒馆中为一张传说卡牌而大大出手。甚至就连神明也亲',
        'readingType': 5,
        'algInfo': '',
        'adid': 0,
        'overrating': null,
        'sourceType': 0,
        'sourceDesc': null,
        'authorTagId': '明星|种田文|赚钱',
        'bookInternalId': 5841993,
        'prob': 0,
        'recommendRate': null,
        'staticscore1': 5423
      }]
    }).list;
    return {
      status: 200,
      data: all,
    };
  },
  '/api/v1/history': ({ method, url, params, urlparams, headers }) => {
    const all = Mock.mock({
      'list|2': [{
        'bookId|+1': 1006853204,
        'bookName': '文化入侵异世界',
        'authorId': 3112022,
        'author': '姐姐的新娘',
        'isVip': 1,
        'imageStatus': 1,
        'lastUpdateChapterID': 376292828,
        'lastUpdateChapterName': '第三百零一章 过时',
        'lastChapterUpdateTime': 1506786023000,
        'lastVipUpdateChapterId': 387124661,
        'lastVipUpdateChapterName': '第三百零一章 过时',
        'lastVipChapterUpdateTime': 1506786023000,
        'wordsCount': 682009,
        'categoryName': '科幻',
        'subCategoryName': '时空穿梭',
        'categoryId': 100117,
        'bookStatus': '连载',
        'enableBookUnitBuy': 0,
        'enableBookUnitLease': 0,
        'bssReadTotal': 685864,
        'bssRecomTotal': 152538,
        'label': '明星|种田文|赚钱',
        'description': '一群巨龙搬着小板凳日夜追看《权力游戏》。精灵大德鲁伊们因为《忠犬八公的故事》而潸然泪下。人类与矮人在《炉石传说》酒馆中为一张传说卡牌而大大出手。甚至就连神明也亲',
        'readingType': 5,
        'algInfo': '',
        'adid': 0,
        'overrating': null,
        'sourceType': 0,
        'sourceDesc': null,
        'authorTagId': '明星|种田文|赚钱',
        'bookInternalId': 5841993,
        'prob': 0,
        'recommendRate': null,
        'staticscore1': 5423
      }]
    }).list;
    return {
      status: 200,
      data: all,
    };
  },
  '/api/v1/books/{id}': ({ method, url, params, urlparams, headers }) => {
    const obj = Mock.mock({
      'obj': {
        'BookId': 1209977,
        'BookName': '斗破苍穹',
        'AuthorId': 1019021,
        'Author': '天蚕土豆',
        'ChannelId': 1,
        'ChannelName': '奇幻·玄幻',
        'WordsCnt': 5194967,
        'CategoryId': 21,
        'CategoryName': '玄幻',
        'SubCategoryName': '异世大陆',
        'SubCategoryId': 73,
        'CollectCnt': 1532249,
        'ShowTime': 0,
        'BookIntro': null,
        'ForumId': 0,
        'FreeType': 1,
        'ImageStatus': 1,
        'RecommendAll': 6693122,
        'ClickAll': 150655136,
        'ClickMonth': 114,
        'ClickWeek': 60,
        'VoteAll': 6693122,
        'VoteMonth': 379,
        'VoteWeek': 180,
        'LastVipUpdateChapterId': 23720626,
        'LastVipUpdateChapterName': '新书大主宰已发。',
        'LastVipChapterUpdateTime': 1372821505000,
        'LastUpdateChapterID': 23720626,
        'LastUpdateChapterName': '第九十五章 眼光挺差',
        'LastChapterUpdateTime': 1243770561000,
        'AuthorOtherBooksCount': 2,
        'BookFansCount': 3392723,
        'LastUpdateChapter': '',
        'LastUpdateVipChapter': '',
        'IsMeng': 0,
        'IsVip': 1,
        'BookStatus': '完本',
        'SignStatus': 'Ａ级签约',
        'IsCanDaShang': 1,
        'IscanPraise': 0,
        'IsQin': 0,
        'YinXiang': {
          'Enable': 1,
          'LabelList': [{
            'Name': '热血',
            'Count': 7
          }, {
            'Name': '斗气',
            'Count': 6
          }, {
            'Name': '小白',
            'Count': 5
          }, {
            'Name': '奋斗',
            'Count': 2
          }, {
            'Name': '淡定',
            'Count': 2
          }, {
            'Name': '励志',
            'Count': 1
          }, {
            'Name': '爽文',
            'Count': 1
          }, {
            'Name': '胖子',
            'Count': 1
          }],
          'DefaultLabel': null
        },
        'RpId': 0,
        'From': '起点中文网',
        'WholeSale': 0,
        'TotalPrice': 0,
        'Chapters': null,
        'Volumes': null,
        'FirstVipChapterId': 0,
        'FirstUnitId': 0,
        'BookHonor': [{
          'Honors': '精品频道',
          'Time': 1373230801000,
          'HonorType': 'Badge',
          'HonorICON': 'https://qidian.gtimg.com/qd/images/book/badges/84jingpinpindao.png',
          'HonorSubTitle': '被收录入精品频道'
        }, {
          'Honors': '习惯性爆发',
          'Time': 1340764715000,
          'HonorType': 'Badge',
          'HonorICON': 'https://qidian.gtimg.com/qd/images/book/badges/84xiguanxingbaofa.png',
          'HonorSubTitle': '正式章节10次以上日更万字'
        }, {
          'Honors': '日进斗金',
          'Time': 1331775390000,
          'HonorType': 'Badge',
          'HonorICON': 'https://qidian.gtimg.com/qd/images/book/badges/84rijindoujin.png',
          'HonorSubTitle': '单天获得100W起点币的打赏'
        }, {
          'Honors': '谢主隆恩',
          'Time': 1331706961000,
          'HonorType': 'Badge',
          'HonorICON': 'https://qidian.gtimg.com/qd/images/book/badges/84xiezhulongen.png',
          'HonorSubTitle': '获得过10000次打赏'
        }, {
          'Honors': '月票第一',
          'Time': 1331615746000,
          'HonorType': 'Badge',
          'HonorICON': 'https://qidian.gtimg.com/qd/images/book/badges/84yuepiaodiyi.png',
          'HonorSubTitle': '曾经获得过单月月票榜第一'
        }, {
          'Honors': '百盟争霸',
          'Time': 1330072635000,
          'HonorType': 'Badge',
          'HonorICON': 'https://qidian.gtimg.com/qd/images/book/badges/84baimengzhengba.png',
          'HonorSubTitle': '拥有100个及以上盟主级别粉丝'
        }, {
          'Honors': '更上一层楼',
          'Time': 1249401600000,
          'HonorType': 'Badge',
          'HonorICON': 'https://qidian.gtimg.com/qd/images/book/badges/84gengshangyicenglou.png',
          'HonorSubTitle': '连续30天至少日更3000字'
        }],
        'AuthorInfo': {
          'RealImageUrl': 'https://qidian.qpic.cn/qd_face/349573/520843/100',
          'AuthorDesc': '网络文学资深玄幻小说作家',
          'AuthorBook': '著有《斗破苍穹》《武动乾坤》《大主宰》',
          'UserId': 20224457,
          'IsFollow': 0,
          'AuthorId': 1019021,
          'AuthorName': '天蚕土豆',
          'AuthorLevel': 'Lv5',
          'AuthorLevelId': 3,
          'Books': null,
          'AuthorWordsCount': 0,
          'WriteDayCount': 0,
          'AuthorFansCount': 8655340,
          'AuthorDynamic': null,
          'DynamicInfo': null,
          'AuthorTitleInfo': null,
          'NewBookNoticeInfoList': null,
          'TABookList': null,
          'YOUTABookList': null
        },
        'AuthorRecommend': [{
          'BookId': 2048120,
          'BookName': '武动乾坤',
          'AuthorId': 1019021,
          'AuthorName': '',
          'Author': '天蚕土豆',
          'CategoryId': 21,
          'CategoryName': '玄幻',
          'ImageStatus': 1,
          'LastUpdateChapterID': 34384468,
          'LastUpdateChapterName': '第九十三章 古大师',
          'LastChapterUpdateTime': 1314781451000,
          'LastVipUpdateChapterId': 34384468,
          'LastVipUpdateChapterName': '新书大主宰已发。',
          'LastVipChapterUpdateTime': 1372821529000,
          'IsVip': 1,
          'BookStatus': '完本',
          'WordsCount': 0,
          'Label': null,
          'IsQin': 0,
          'BssReadTotal': 73026504,
          'BssRecomTotal': 739104,
          'Price': null,
          'NewPrice': null,
          'Recommendation': null,
          'RecommenId': 0,
          'GroupName': '作者还写过',
          'ReadingType': 5,
          'AlgInfo': '',
          'PartCount': 0,
          'SourceBookId': 0,
          'BookPartInfo': null,
          'ChargeType': 0,
          'TotalPrice': 0,
          'Description': '修炼一途，乃窃阴阳，夺造化，转涅盘，握生死，掌轮回。武之极，...'
        }, {
          'BookId': 2750457,
          'BookName': '大主宰',
          'AuthorId': 1019021,
          'AuthorName': '',
          'Author': '天蚕土豆',
          'CategoryId': 21,
          'CategoryName': '玄幻',
          'ImageStatus': 1,
          'LastUpdateChapterID': 47024266,
          'LastUpdateChapterName': '我的第四本书要上架了，请大家内详。',
          'LastChapterUpdateTime': 1375260889000,
          'LastVipUpdateChapterId': 47024266,
          'LastVipUpdateChapterName': '第一千五百五十一章 邪神陨落（大结局）',
          'LastVipChapterUpdateTime': 1499518184000,
          'IsVip': 1,
          'BookStatus': '完本',
          'WordsCount': 0,
          'Label': null,
          'IsQin': 0,
          'BssReadTotal': 36651788,
          'BssRecomTotal': 1590024,
          'Price': null,
          'NewPrice': null,
          'Recommendation': null,
          'RecommenId': 0,
          'GroupName': '作者还写过',
          'ReadingType': 5,
          'AlgInfo': '',
          'PartCount': 0,
          'SourceBookId': 0,
          'BookPartInfo': null,
          'ChargeType': 0,
          'TotalPrice': 0,
          'Description': '大千世界，位面交汇，万族林立，群雄荟萃，一位位来自下位面的天...'
        }],
        'BookFriendsRecommend': [{
          'BookId': 2180332,
          'BookName': '肌肉魔法师',
          'AuthorId': 2336208,
          'AuthorName': '',
          'Author': '烟雨织轻愁',
          'CategoryId': 21,
          'CategoryName': '玄幻',
          'ImageStatus': 1,
          'LastUpdateChapterID': 49853232,
          'LastUpdateChapterName': '第六十六章：大结局',
          'LastChapterUpdateTime': 1386639877000,
          'LastVipUpdateChapterId': 49853232,
          'LastVipUpdateChapterName': '',
          'LastVipChapterUpdateTime': -62135798400000,
          'IsVip': 0,
          'BookStatus': '完本',
          'WordsCount': 0,
          'Label': null,
          'IsQin': 0,
          'BssReadTotal': 16884,
          'BssRecomTotal': 100,
          'Price': null,
          'NewPrice': null,
          'Recommendation': null,
          'RecommenId': 0,
          'GroupName': '书友还看过',
          'ReadingType': 4,
          'AlgInfo': '180.7.2',
          'PartCount': 0,
          'SourceBookId': 0,
          'BookPartInfo': null,
          'ChargeType': 0,
          'TotalPrice': 0,
          'Description': '流氓不可怕，可怕流氓有文化！魔法师不可怕，可怕魔法师有肌肉！什么？你是魔法师？我也是魔法师，并且我敢保证，我施展魔法比你快！什么？你是武士？不好意思，我是炼体士，凭你的攻击，根本就破不了我的防！重生后的林飞，完美地利用前世的种种机缘，一步步地踏上巅峰！这一世，势不留下遗憾！'
        }, {
          'BookId': 3506478,
          'BookName': '妖神记',
          'AuthorId': 1038481,
          'AuthorName': '',
          'Author': '发飙的蜗牛',
          'CategoryId': 21,
          'CategoryName': '玄幻',
          'ImageStatus': 1,
          'LastUpdateChapterID': 86286632,
          'LastUpdateChapterName': '第一百三十二章 拳刺（急求推荐票！！）',
          'LastChapterUpdateTime': 1438326101000,
          'LastVipUpdateChapterId': 86286632,
          'LastVipUpdateChapterName': '第四百五十七章 女弟子',
          'LastVipChapterUpdateTime': 1505014046000,
          'IsVip': 1,
          'BookStatus': '连载',
          'WordsCount': 0,
          'Label': null,
          'IsQin': 0,
          'BssReadTotal': 3058603,
          'BssRecomTotal': 183410,
          'Price': null,
          'NewPrice': null,
          'Recommendation': null,
          'RecommenId': 0,
          'GroupName': '书友还看过',
          'ReadingType': 5,
          'AlgInfo': '180.7.2',
          'PartCount': 0,
          'SourceBookId': 0,
          'BookPartInfo': null,
          'ChargeType': 0,
          'TotalPrice': 0,
          'Description': '妖神重生，谁与争锋。这是一个妖灵的世界，人们猎杀妖兽，获取妖灵，将妖灵融入灵魂海中，就可以获得强大的力量。因为一本时空妖灵之书，聂离回到了年少的时代……~~《妖神记》是蜗牛精心雕琢的一部玄幻作品，将会是一部与众不同的玄幻故事，另外《妖神记》的漫画也在腾讯动漫同时发布，画风非常精美，请大家多多支持。~~'
        }, {
          'BookId': 1004853354,
          'BookName': '天主凡人',
          'AuthorId': 3327498,
          'AuthorName': '',
          'Author': '落十方',
          'CategoryId': 21,
          'CategoryName': '玄幻',
          'ImageStatus': 1,
          'LastUpdateChapterID': 369180392,
          'LastUpdateChapterName': '关于粉丝节及新书一事【完本】',
          'LastChapterUpdateTime': 1493993807000,
          'LastVipUpdateChapterId': 369180392,
          'LastVipUpdateChapterName': '',
          'LastVipChapterUpdateTime': -62135798400000,
          'IsVip': 0,
          'BookStatus': '完本',
          'WordsCount': 0,
          'Label': null,
          'IsQin': 0,
          'BssReadTotal': 26138,
          'BssRecomTotal': 1815,
          'Price': null,
          'NewPrice': null,
          'Recommendation': null,
          'RecommenId': 0,
          'GroupName': '书友还看过',
          'ReadingType': 4,
          'AlgInfo': '180.7.2',
          'PartCount': 0,
          'SourceBookId': 0,
          'BookPartInfo': null,
          'ChargeType': 0,
          'TotalPrice': 0,
          'Description': '乱古岁月，群星陨落，日月颠离，天地一片黯淡。古老浩瀚的天穹之城，遮日月，蔽星芒，被天地所暗藏。这里，人族卑微似蝼蚁，而万族强盛，群魔乱舞。试问诸天万族，执子博天，又有谁人跳出这天穹枷锁？少年出自天穹之城，闯入浩瀚无尽的神秘世界，世间沧海一栗由此揭开。'
        }, {
          'BookId': 163560,
          'BookName': '恶魔法则',
          'AuthorId': 4362305,
          'AuthorName': '',
          'Author': '跳舞',
          'CategoryId': 21,
          'CategoryName': '玄幻',
          'ImageStatus': 1,
          'LastUpdateChapterID': 22272211,
          'LastUpdateChapterName': '第八十一章 【青春不老泉的副作用】',
          'LastChapterUpdateTime': 1231329030000,
          'LastVipUpdateChapterId': 22272211,
          'LastVipUpdateChapterName': '【恶魔法则后传已经开始了！】',
          'LastVipChapterUpdateTime': 1363924877000,
          'IsVip': 1,
          'BookStatus': '完本',
          'WordsCount': 0,
          'Label': null,
          'IsQin': 0,
          'BssReadTotal': 39180234,
          'BssRecomTotal': 561684,
          'Price': null,
          'NewPrice': null,
          'Recommendation': null,
          'RecommenId': 0,
          'GroupName': '书友还看过',
          'ReadingType': 5,
          'AlgInfo': '180.7.2',
          'PartCount': 0,
          'SourceBookId': 0,
          'BookPartInfo': null,
          'ChargeType': 0,
          'TotalPrice': 0,
          'Description': '一个一无是处的，被认为是废物和白痴家伙，把灵魂卖给了恶魔，能换取到什么？美色？力量？财富？权力？颠覆这世界的所有规则吧，让我们遵寻着恶魔的轨迹……“我知道，终有一天，这个世界将被我踩在脚下！！”——杜维<a target=\'_11ank\'href=\'http://bookstore.qidian.com/ploy/vip7years/index.html#five\'>抢购实体书，尽享五重惊喜好礼</a>'
        }, {
          'BookId': 2048120,
          'BookName': '武动乾坤',
          'AuthorId': 1019021,
          'AuthorName': '',
          'Author': '天蚕土豆',
          'CategoryId': 21,
          'CategoryName': '玄幻',
          'ImageStatus': 1,
          'LastUpdateChapterID': 34384468,
          'LastUpdateChapterName': '第九十三章 古大师',
          'LastChapterUpdateTime': 1314781451000,
          'LastVipUpdateChapterId': 34384468,
          'LastVipUpdateChapterName': '新书大主宰已发。',
          'LastVipChapterUpdateTime': 1372821529000,
          'IsVip': 1,
          'BookStatus': '完本',
          'WordsCount': 0,
          'Label': null,
          'IsQin': 0,
          'BssReadTotal': 73026504,
          'BssRecomTotal': 739104,
          'Price': null,
          'NewPrice': null,
          'Recommendation': null,
          'RecommenId': 0,
          'GroupName': '书友还看过',
          'ReadingType': 5,
          'AlgInfo': '180.7.2',
          'PartCount': 0,
          'SourceBookId': 0,
          'BookPartInfo': null,
          'ChargeType': 0,
          'TotalPrice': 0,
          'Description': '修炼一途，乃窃阴阳，夺造化，转涅盘，握生死，掌轮回。武之极，破苍穹，动乾坤！'
        }, {
          'BookId': 1777445,
          'BookName': '天珠变',
          'AuthorId': 4921,
          'AuthorName': '',
          'Author': '唐家三少',
          'CategoryId': 21,
          'CategoryName': '玄幻',
          'ImageStatus': 1,
          'LastUpdateChapterID': 30642374,
          'LastUpdateChapterName': '第二十四章 白色小老虎（三）',
          'LastChapterUpdateTime': 1293795548000,
          'LastVipUpdateChapterId': 30642374,
          'LastVipUpdateChapterName': '麻烦大家把推荐票投给新书《神印王座》',
          'LastVipChapterUpdateTime': 1321883172000,
          'IsVip': 1,
          'BookStatus': '完本',
          'WordsCount': 0,
          'Label': null,
          'IsQin': 0,
          'BssReadTotal': 34620345,
          'BssRecomTotal': 366151,
          'Price': null,
          'NewPrice': null,
          'Recommendation': null,
          'RecommenId': 0,
          'GroupName': '书友还看过',
          'ReadingType': 5,
          'AlgInfo': '180.7.2',
          'PartCount': 0,
          'SourceBookId': 0,
          'BookPartInfo': null,
          'ChargeType': 0,
          'TotalPrice': 0,
          'Description': '人有本命珠，觉醒后或为意珠、或为体珠，如手串分别在左右手腕处盘旋。天珠如人类之双胞胎，当意、体双珠同时出现在一个人身上的时候，即为天珠。修炼体珠者是为体珠师，修炼意珠者是为意珠师，而修炼天珠者自然即是天珠师。天珠师最高为十二双珠，因此，它的修炼过程也被称之为：天珠十二变。我们的主角就是一位修炼着天珠变的弓箭手。'
        }, {
          'BookId': 1524659,
          'BookName': '异世邪君',
          'AuthorId': 4362475,
          'AuthorName': '',
          'Author': '风凌天下',
          'CategoryId': 21,
          'CategoryName': '玄幻',
          'ImageStatus': 1,
          'LastUpdateChapterID': 27573427,
          'LastUpdateChapterName': '上架感言',
          'LastChapterUpdateTime': 1272653014000,
          'LastVipUpdateChapterId': 27573427,
          'LastVipUpdateChapterName': '新书《天域苍穹》登陆起点！希望大家支持！',
          'LastVipChapterUpdateTime': 1421738505000,
          'IsVip': 1,
          'BookStatus': '完本',
          'WordsCount': 0,
          'Label': null,
          'IsQin': 0,
          'BssReadTotal': 33596286,
          'BssRecomTotal': 261100,
          'Price': null,
          'NewPrice': null,
          'Recommendation': null,
          'RecommenId': 0,
          'GroupName': '书友还看过',
          'ReadingType': 5,
          'AlgInfo': '180.7.2',
          'PartCount': 0,
          'SourceBookId': 0,
          'BookPartInfo': null,
          'ChargeType': 0,
          'TotalPrice': 0,
          'Description': '世间毁誉，世人冷眼，与我何干？我自淡然一笑；以吾本性，快意恩仇，以吾本心，遨游世间，我命由我不由天！一代牛人穿越异界，看其如何踏上异世巅峰，成为一代邪君！'
        }],
        'SameRecommend': [{
          'BookId': 1010474452,
          'BookName': '大自在天尊',
          'AuthorId': 3021189,
          'AuthorName': '',
          'Author': '零下5度01',
          'CategoryId': 21,
          'CategoryName': '玄幻',
          'ImageStatus': 0,
          'LastUpdateChapterID': 387249174,
          'LastUpdateChapterName': '第六十九章：怨灵！（求推荐，求收藏）',
          'LastChapterUpdateTime': 1506931857000,
          'LastVipUpdateChapterId': 0,
          'LastVipUpdateChapterName': '',
          'LastVipChapterUpdateTime': 0,
          'IsVip': 0,
          'BookStatus': '连载',
          'WordsCount': 0,
          'Label': null,
          'IsQin': 0,
          'BssReadTotal': 193657,
          'BssRecomTotal': 26381,
          'Price': null,
          'NewPrice': null,
          'Recommendation': null,
          'RecommenId': 0,
          'GroupName': '同类作品',
          'ReadingType': 4,
          'AlgInfo': '',
          'PartCount': 0,
          'SourceBookId': 0,
          'BookPartInfo': null,
          'ChargeType': 0,
          'TotalPrice': 0,
          'Description': '林云本为天龙寺俗家弟子，却被同门诬陷，身犯戒律，被打入‘死地...'
        }, {
          'BookId': 1010274800,
          'BookName': '终极村长',
          'AuthorId': 400684092,
          'AuthorName': '',
          'Author': '顷刻兴亡过手',
          'CategoryId': 21,
          'CategoryName': '玄幻',
          'ImageStatus': 0,
          'LastUpdateChapterID': 387200568,
          'LastUpdateChapterName': '九十六 申猴',
          'LastChapterUpdateTime': 1506868992000,
          'LastVipUpdateChapterId': 0,
          'LastVipUpdateChapterName': '',
          'LastVipChapterUpdateTime': 0,
          'IsVip': 0,
          'BookStatus': '连载',
          'WordsCount': 0,
          'Label': null,
          'IsQin': 0,
          'BssReadTotal': 8474,
          'BssRecomTotal': 2970,
          'Price': null,
          'NewPrice': null,
          'Recommendation': null,
          'RecommenId': 0,
          'GroupName': '同类作品',
          'ReadingType': 4,
          'AlgInfo': '',
          'PartCount': 0,
          'SourceBookId': 0,
          'BookPartInfo': null,
          'ChargeType': 0,
          'TotalPrice': 0,
          'Description': '当七十亿人类被一脚踹进牢笼。诸子百家复活于世。小说神话捏成一...'
        }, {
          'BookId': 1010450940,
          'BookName': '人道崛起',
          'AuthorId': 5012945,
          'AuthorName': '',
          'Author': '山人有妙计',
          'CategoryId': 21,
          'CategoryName': '玄幻',
          'ImageStatus': 0,
          'LastUpdateChapterID': 387239960,
          'LastUpdateChapterName': '第八十九章 流言消息 倔强少年！',
          'LastChapterUpdateTime': 1506930900000,
          'LastVipUpdateChapterId': 0,
          'LastVipUpdateChapterName': '',
          'LastVipChapterUpdateTime': 0,
          'IsVip': 0,
          'BookStatus': '连载',
          'WordsCount': 0,
          'Label': null,
          'IsQin': 0,
          'BssReadTotal': 41117,
          'BssRecomTotal': 16055,
          'Price': null,
          'NewPrice': null,
          'Recommendation': null,
          'RecommenId': 0,
          'GroupName': '同类作品',
          'ReadingType': 4,
          'AlgInfo': '',
          'PartCount': 0,
          'SourceBookId': 0,
          'BookPartInfo': null,
          'ChargeType': 0,
          'TotalPrice': 0,
          'Description': '大荒之地，万族奔放，野蛮生长，正值人族圣人未出之时，万族生存...'
        }, {
          'BookId': 1010472915,
          'BookName': '翻天鉴',
          'AuthorId': 4362958,
          'AuthorName': '',
          'Author': '竹上猪猪',
          'CategoryId': 21,
          'CategoryName': '玄幻',
          'ImageStatus': 0,
          'LastUpdateChapterID': 387245182,
          'LastUpdateChapterName': '六十三章 林间贵女',
          'LastChapterUpdateTime': 1506928434000,
          'LastVipUpdateChapterId': 0,
          'LastVipUpdateChapterName': '',
          'LastVipChapterUpdateTime': 0,
          'IsVip': 0,
          'BookStatus': '连载',
          'WordsCount': 0,
          'Label': null,
          'IsQin': 0,
          'BssReadTotal': 28844,
          'BssRecomTotal': 8600,
          'Price': null,
          'NewPrice': null,
          'Recommendation': null,
          'RecommenId': 0,
          'GroupName': '同类作品',
          'ReadingType': 4,
          'AlgInfo': '',
          'PartCount': 0,
          'SourceBookId': 0,
          'BookPartInfo': null,
          'ChargeType': 0,
          'TotalPrice': 0,
          'Description': '机缘巧合之下捡到一口神秘钵盂，自此人生一发不可收拾！种种神功...'
        }, {
          'BookId': 1010470461,
          'BookName': '万界通讯录',
          'AuthorId': 6900487,
          'AuthorName': '',
          'Author': '鱼儿大虾',
          'CategoryId': 21,
          'CategoryName': '玄幻',
          'ImageStatus': 0,
          'LastUpdateChapterID': 387261145,
          'LastUpdateChapterName': '第五十九章 你清哥太小气',
          'LastChapterUpdateTime': 1506941537000,
          'LastVipUpdateChapterId': 0,
          'LastVipUpdateChapterName': '',
          'LastVipChapterUpdateTime': 0,
          'IsVip': 0,
          'BookStatus': '连载',
          'WordsCount': 0,
          'Label': null,
          'IsQin': 0,
          'BssReadTotal': 9118,
          'BssRecomTotal': 1682,
          'Price': null,
          'NewPrice': null,
          'Recommendation': null,
          'RecommenId': 0,
          'GroupName': '同类作品',
          'ReadingType': 4,
          'AlgInfo': '',
          'PartCount': 0,
          'SourceBookId': 0,
          'BookPartInfo': null,
          'ChargeType': 0,
          'TotalPrice': 0,
          'Description': '“我真是萧炎，我要给你说一件不可思议的事，我穿越了。说起来你...'
        }, {
          'BookId': 1009233711,
          'BookName': '西游之黑山妖君',
          'AuthorId': 11806758,
          'AuthorName': '',
          'Author': '猫虔',
          'CategoryId': 21,
          'CategoryName': '玄幻',
          'ImageStatus': 0,
          'LastUpdateChapterID': 387177415,
          'LastUpdateChapterName': '第五十四章 为山九仞',
          'LastChapterUpdateTime': 1506862800000,
          'LastVipUpdateChapterId': 0,
          'LastVipUpdateChapterName': '',
          'LastVipChapterUpdateTime': 0,
          'IsVip': 0,
          'BookStatus': '连载',
          'WordsCount': 0,
          'Label': null,
          'IsQin': 0,
          'BssReadTotal': 6902,
          'BssRecomTotal': 1867,
          'Price': null,
          'NewPrice': null,
          'Recommendation': null,
          'RecommenId': 0,
          'GroupName': '同类作品',
          'ReadingType': 4,
          'AlgInfo': '',
          'PartCount': 0,
          'SourceBookId': 0,
          'BookPartInfo': null,
          'ChargeType': 0,
          'TotalPrice': 0,
          'Description': '西游世界，漫天神佛，遍地妖魔！附身为一头斑斓大虫，如何在危机...'
        }, {
          'BookId': 1010537768,
          'BookName': '神话搬运工',
          'AuthorId': 400965222,
          'AuthorName': '',
          'Author': '三只毛',
          'CategoryId': 21,
          'CategoryName': '玄幻',
          'ImageStatus': 0,
          'LastUpdateChapterID': 387236701,
          'LastUpdateChapterName': '第四十九章，神龙带你飞',
          'LastChapterUpdateTime': 1506935100000,
          'LastVipUpdateChapterId': 0,
          'LastVipUpdateChapterName': '',
          'LastVipChapterUpdateTime': 0,
          'IsVip': 0,
          'BookStatus': '连载',
          'WordsCount': 0,
          'Label': null,
          'IsQin': 0,
          'BssReadTotal': 7609,
          'BssRecomTotal': 1907,
          'Price': null,
          'NewPrice': null,
          'Recommendation': null,
          'RecommenId': 0,
          'GroupName': '同类作品',
          'ReadingType': 4,
          'AlgInfo': '',
          'PartCount': 0,
          'SourceBookId': 0,
          'BookPartInfo': null,
          'ChargeType': 0,
          'TotalPrice': 0,
          'Description': '身具造化神术的元霄在仙界身死后转世为异世界洛家独子——洛霄。...'
        }],
        'EnableBookUnitLease': 0,
        'EnableBookUnitBuy': 0,
        'UnitCount': 0,
        'UnitBuyCount': 0,
        'BssReadTotal': 157859464,
        'BssRecomTotal': 1532644,
        'TotalChapterCount': 1655,
        'BookFansList': [{
          'UserId': 108459327,
          'NickName': 'parkourman',
          'RealImageUrl': 'https://qidian.qpic.cn/qd_face/349573/538763/100',
          'Amount': 8653401,
          'RankName': '盟主',
          'Rank': 0,
          'OrderId': 0
        }, {
          'UserId': 120427008,
          'NickName': '右掱邊~\u000E',
          'RealImageUrl': 'https://qidian.qpic.cn/qd_face/349573/544389/100',
          'Amount': 3040250,
          'RankName': '盟主',
          'Rank': 0,
          'OrderId': 0
        }],
        'BookReviewList': [{
          'RankName': '',
          'Id': 1110019189,
          'ViewCount': 1,
          'PostCount': 1,
          'Subject': '',
          'UserName': '爱他与其不爱他',
          'UserId': 301498704,
          'PostDate': 1499517867000,
          'Body': '推部签约小说《重生之千金有点拽》，堪称小说版的《回家的诱惑》，写作手法另类，是小说界的一股清流！大家可搜《重生之千金有点拽》，或搜作者：安子科[fn=31]『已签约，阅文编辑都肯定了，你还犹豫什么？』\n\n\n\n\n\n\n\n\n\n谢谢作者的平台[fn=43]，愿作者在这个月身价过亿[fn=2][fn=2]',
          'Type': 0,
          'VoteYes': 0,
          'VoteAgainst': 0,
          'UserHeadIcon': 'https://me.qidian.com/Images/UserImages/100x100/120.jpg',
          'From': 'Android 客户端'
        }, {
          'RankName': '',
          'Id': 1109991234,
          'ViewCount': 0,
          'PostCount': 0,
          'Subject': '',
          'UserName': '岁月的孽缘',
          'UserId': 227037855,
          'PostDate': 1499508002000,
          'Body': '水个广告\uD83D\uDE01\uD83D\uDE01\uD83D\uDE01\uD83D\uDE01\uD83D\uDE01\n《斗破苍穹之大陆起源》\n求收藏！求推荐票！',
          'Type': 0,
          'VoteYes': 0,
          'VoteAgainst': 0,
          'UserHeadIcon': 'https://qidian.qpic.cn/qd_face/349573/3784908/100',
          'From': 'Android 客户端'
        }, {
          'RankName': '',
          'Id': 1109986143,
          'ViewCount': 0,
          'PostCount': 0,
          'Subject': '',
          'UserName': '浊酒任逍遥',
          'UserId': 230952612,
          'PostDate': 1499506225000,
          'Body': '《求仙策》萌新仙侠好书，在上仙侠分类强推中，本想写些比较牛逼的广告语，结果想半天没想出来，算了，这一次少点套路，多点真诚，各位老铁看了觉得可以的话，不妨加入书架支持下呗～',
          'Type': 0,
          'VoteYes': 0,
          'VoteAgainst': 0,
          'UserHeadIcon': 'https://me.qidian.com/Images/UserImages/100x100/181.jpg',
          'From': 'iOS 客户端'
        }, {
          'RankName': '',
          'Id': 1109977911,
          'ViewCount': 0,
          'PostCount': 0,
          'Subject': '',
          'UserName': '悠哉游哉呵呵',
          'UserId': 196888599,
          'PostDate': 1499502687000,
          'Body': '还是当初高中晚上拿着诺基亚躲被窝偷偷看的(ಡωಡ)hiahiahia ',
          'Type': 0,
          'VoteYes': 0,
          'VoteAgainst': 0,
          'UserHeadIcon': 'https://qidian.qpic.cn/qd_face/349573/2668615/100',
          'From': 'Android 客户端'
        }, {
          'RankName': '',
          'Id': 1109974882,
          'ViewCount': 0,
          'PostCount': 0,
          'Subject': '',
          'UserName': '月梓心love',
          'UserId': 229065450,
          'PostDate': 1499501300000,
          'Body': '         带书来土豆这里推一下，《南笙有你》，现代小说，没有浮夸的剧情更没有狗血般的爱恨情仇，有的只是对爱情的纯洁，对幸福的向往，以及对背叛的宽容与谅解。\n        在现代这个社会里，或许没有浮夸的“人吃人”，但依旧存在着人们之间的勾心斗角，明争暗斗。\n        或许，你们不喜欢这样的生活，《南笙有你》或许不是你的菜，但希望走过可你看看，喜欢就来瞧瞧！\n         说真的，不喜欢推书，但起点被发现的几率太小，所以，这也是无可奈何的事情~\n         谢谢~\n',
          'Type': 0,
          'VoteYes': 0,
          'VoteAgainst': 0,
          'UserHeadIcon': 'https://me.qidian.com/Images/UserImages/100x100/120.jpg',
          'From': 'Android 客户端'
        }],
        'MTMBookInfo': null,
        'MonthTicketCount': 122,
        'DonateCount': 51816,
        'BookForumCount': 528708,
        'CategoryPicture': 'http://h5.if.qidian.com/Content/images/categorybg/玄幻_奇幻_玄幻言情.jpg',
        'CategoryActionUrl': '',
        'CopyRight': '2009-04-14上架\n本作品由作家天蚕土豆授权起点中文网独家首发\n版权所有·侵权必究',
        'BookStar': 4,
        'QQBookID': 0,
        'IsOutBook': 0,
        'IsOffline': 0,
        'LastWeekWordsUpadteCnt': 0,
        'RecommendWord': '最热小说，不容错过的巅峰之作',
        'AroundInfos': [],
        'EnableVoteMonth': 1,
        'EnableDonate': 1,
        'HongBao': null,
        'AudioInfo': {
          'IsFreeLimit': 0,
          'IsFreeLimitMsg': '',
          'RemainingTime': 0,
          'EndTime': 0,
          'Adid': 8159970304288701,
          'AudioName': '斗破苍穹',
          'AnchorId': 8159970303489001,
          'AnchorName': '领先声创',
          'AuthorId': 1019021,
          'AuthorName': '天蚕土豆',
          'BookId': 1209977,
          'Site': 10,
          'RecordText': '',
          'FreeType': 3,
          'CategoryId': 80001,
          'SubcategoryId': 80055,
          'AudioType': 0,
          'AllAudioChapters': 75,
          'AllChapterSize': 285.36,
          'BitRate': 64,
          'CoverUrl': 'http://img1.write.qq.com/upload/cover/2016-12-13/584fbe6d577ea.jpg',
          'Intro': '这里是属于斗气的世界，没有花俏艳丽的魔法，有的，仅仅是繁衍到巅峰的斗气！\r\n新书等级制度：斗者，斗师，大斗师，斗灵，斗王，斗皇，斗宗，斗尊，斗圣，斗帝。\r\n\n',
          'ChargeType': 3,
          'Price': 20,
          'StartChargeChapterSort': 6000,
          'LastChapterId': 23185087431779401,
          'LastChapterName': '第75集 大手笔',
          'Csuuid': 105,
          'ScheduleStatus': 1,
          'Creator': '陆洁红',
          'Status': 1,
          'CreateTime': 1501641303000,
          'UpdateTime': 1506412835000,
          'LastUpdateTime': 1506848428000,
          'ChapterIndex': 75,
          'CbId': 0
        },
        'SourceBookId': 0,
        'BookPartInfo': {
          'Position': 0,
          'BookPartList': []
        },
        'Description': '这里是属于斗气的世界，没有花俏艳丽的魔法，有的，仅仅是繁衍到巅峰的斗气！新书等级制度：斗者，斗师，大斗师，斗灵，斗王，斗皇，斗宗，斗尊，斗圣，斗帝。',
        'Game': null
      }
    }).obj;
    return {
      status: 200,
      data: obj,
    };
  },
  '/api/v1/books/{bookId}/{chapterId}/content': ({ method, url, params, urlparams, headers }) => {
    const urlx = parseInt(urlparams.chapterId);
    console.log(urlx);
    let all;
    switch(urlx){
    case 247:
    {
      all = Mock.mock({
        'obj':{
          'Result': 0,
          'Message': '成功',
          'Data': '　　都说人不中二枉少年。\r\n　　每个人或多或少都经历过那个时期，只是有些人表现出来，有些人则藏在心底。也就是明骚和暗骚的区别。\r\n　　宋书航有些少年老成，那个时期来的快，去的更快。\r\n　　所以到了初中二年级时，周围男孩还陷在武侠梦、超人梦、仙人梦，整天挥舞着降龙十八掌、超人变身时。书航却早已经对这些不抱任何希望。\r\n　　这世界的物理法则是如此的精确，一个人类想要一跃三层楼那么高；双掌一拍打出金龙；内裤外穿就能飞翔都是不可能的事情！\r\n　　不过他还是很喜欢仙侠小说、超人电影之类的，或许是他内心深处还是很期望有一天超人啊、外星人啊、仙人啊之类的能出现在他面前吧？\r\n　　明明知道不可能，但却莫名其妙的期待着，这便是人类特有的天赋吧？\r\n　　宋书航笑着关掉群聊天窗口，不过，他没有退出这群。\r\n　　他感觉九洲一号群里的人很有意思，群里那些让人光看到就感觉很羞涩的聊天记录，从旁观者的角度去看的话，意外的很有趣——所以在群主踢人之前，他准备先潜水，看看各种有趣的聊天记录，打发他无聊时的时间。\r\n　　电脑屏幕上，电影还在继续，这好像是一部恐怖片。各种惊悚的剧情层不出断，这部电影是天才恐怖片导演的巅峰之作，据说很多大叔级人物都被吓哭过，有很多人表示被吓的不敢去独自去厕所。\r\n　　可惜，宋书航依旧没感觉到任何可怕之处，重新拉回进度条看了一会儿后，他又打起哈欠，慢慢的从坐姿变为躺姿，眼皮亦越发沉重起来……\r\n　　如果那位天才导演知道自己的电影只有这点效果的话，会哭的吧？\r\n　　迷糊间，宋书航做了个美梦。\r\n　　是个极爽的美梦，美滴很。有仙人，有超人，有各种仙境。\r\n　　长生逍遥，移山倒海，仗剑人间，这是古往今来多少人的梦想？只是随着年龄增长，现实破碎梦想，人们只能将梦藏于心底，不再多想。\r\n　　梦终究是梦……\r\n　　＊＊＊＊＊＊＊＊＊＊\r\n　　次日，5月21日，星期二，凌晨１点。\r\n　　聊天群中，群主黄山真君终于上线。\r\n　　他一上来，北河散人便冒头问道：“真君，昨天你加的那叫‘书山压力大’的是谁？在哪修行的？”\r\n　　“昨天加的人？你们没和她交流吗？那是本尊一位老友在这个时代生的女儿，好像资质不错，年纪轻轻已经是三品后天巅峰，马上就要步入四品先天了，很了不得呢。”黄山真君哈哈一笑，回道。\r\n　　这个时代才出生，那年龄估计不到四十？这个年龄就已经是三品后天巅峰，的确是个天才。北河散人暗暗点头，不过对方取的道号还是很怪啊，‘书山压力大’怎么看都感觉不象是道号。\r\n　　北河散人还在想着呢，黄山真君却突然道：“咦？本尊老友女儿的道号不叫‘书山压力大’啊。话说，这书山压力大是毛玩意？”\r\n　　“……”黄山真君囧了。\r\n　　不是什么毛玩意，是真君您昨天加的未知人类吧。\r\n　　他试探着问道：“真君，您不会是加错人了吧？”\r\n　　“待本尊看看。”\r\n　　片刻后。\r\n　　黄山真君在群里发了一串的冷汗表情：“还真加错了。号码只差中间一位数，本尊将８输成９了。没想到本尊竟然会犯下这种大错。”\r\n　　北河散人呵呵笑道：“我就说呢，就算再怎么融入现代社会，也不会有人将自己的道号定为‘书山压力大’啊。”\r\n　　黄山真君继续发了一串冷汗表情。\r\n　　然后他急忙操作，重新将自己好友女儿拉入群中。\r\n　　群消息提示：‘灵蝶岛羽柔子’已加入九洲一号群。\r\n　　这名字才符合九洲一号群的画风，一股浓郁的仙侠气息扑面而来。那个书山压力大的名称，绝对是混入的奇怪东西。\r\n　　新人一加入，狂刀三浪便马上冒头：“哟，新道友是仙子呐，亮个照，报三围呗！漂亮的话约不约？”\r\n　　狂刀三浪早潜水了很久——他虽然是属金鱼的，但记忆力终究比三秒要长点。昨天已经被人提醒过，所以为了避免得辈大前辈，今天他小心翼翼潜水观察情况。\r\n　　听黄山真君说新加入的仙子是好友之女，而且修为是三品后天，狂刀三浪便放心了。不是‘前辈’级的人物，他可以尽情的调戏一下，过过口瘾。\r\n　　这群里新人很少，他憋的可狠了呢。\r\n　　三浪一开口，黄山真君顿时脸都黑了。\r\n　　“……”灵蝶岛羽柔子输入一串省略号，然后幽幽的又发了一句：“由于时间不早，所以老夫女儿已经按时打坐练功了。她的号码暂时是老夫在挂机，等着黄山道友加群。咳……早就听说九洲群中三浪道友风流倜傥，能说会道，百闻不如一见。三浪道友，老夫欣赏你，改天请你喝酒。”\r\n　　狂刀三浪顿时好生尴尬，调戏妹子却遇上了妹子老爹，这天底下没有比这更羞耻的事了。他好想找个地洞钻进去。\r\n　　好在这位前辈似乎性格随和，轻轻一句话就带过此事。\r\n　　接着，这位前辈和群里在线的众人打了声招呼，请大家将来多多照顾自己女儿。然后，便潜水挂机去了。\r\n　　看到前辈离去，狂刀三浪松了口气，乐呵道：“还好，看样子这位前辈不是开不起玩笑的人。说不定到时候有机会，可以和羽柔子姑娘本人聊聊。”\r\n　　“……”黄山真君。\r\n　　“……”北河散人。\r\n　　药师难得又冒了个头。他是惜字如金的男人，一般很少冒头说话，这次却难得打了四个字：“自求多福。”\r\n　　“？”三浪疑惑。\r\n　　但惜字如金的药师显然不会再多解释。\r\n　　“看新人道号前缀。”北河散人解释道，不作死就不会死，这道理为什么三浪兄永远都不会懂？\r\n　　“前缀？灵蝶岛？”狂刀三浪似乎还没反应过来。\r\n　　“是的，灵蝶岛！再加上是位前辈，你就没想到谁吗？”北河散人提示。\r\n　　半晌后，狂刀三浪恍然大悟，在群中刷了一串‘跪了’的表情：“是那个针针计较灵蝶尊者？”\r\n　　灵蝶尊者是一位强大的前辈，他什么都好，正直侠义……就是喜欢和人计较各种鸡毛蒜皮小事，在斤斤计较的道路上已经登峰造极。别人是斤斤计较，他已经是针针计较！\r\n　　北河散人气的嘴角都抽了：“我可没这么提醒你啊！”\r\n　　黄山真君叹了口气，他实在看不下去了：“三浪，我那老友只是挂机，但还没下线。”\r\n　　也就是说……聊天记录可能会被看到。\r\n　　不，是一定会被看到的！\r\n　　黄山真君实在不能看着三浪继续作死，怎么说也是自己群里的后辈。\r\n　　“我擦，完蛋鸟。”狂刀三浪仿佛看到了不久后的未来，灵蝶仙尊登门拜访，然后对他各种虐的场面。他的眼眶又湿润了，这次似乎惹上了一个更麻烦的大前辈了？\r\n　　三浪顿时惨叫：“真君，请帮我求情啊！”\r\n　　黄山真君给了个冷漠的背影表情。\r\n　　群里人不再理会三浪败犬般的叫声，淡定的转移话题。\r\n　　北河散人问群主道：“真君，那个‘书山压力大’要怎么解决？”\r\n　　苏氏阿七道：“要踢掉吗？毕竟只是普通人，不太好参加我们之间的聊天。”\r\n　　“咳，既然被本尊误加了，那也算是一种缘份吧。让本尊算上一卦，看看怎么处理。”黄山真君回复道——主要是他突然将对方加入了群，现在说踢就踢，他岂不是很没面子？\r\n　　所以至少也算上一卦做做样子，当个借口，再将人踢掉。\r\n　　这样一来显示自己高大上的逼格。\r\n　　二来，他前不久突然对卦算学很感兴趣，学了个把月，正手痒的很。无论干什么事之前，都喜欢算上一卦。\r\n　　说罢他以身边一本《唐诗宋词》起卦，伸手翻动，运转算卦秘术。冥冥中的力量将一句诗词抽出，形成卦像。\r\n　　这次起卦顺利极了，黄山真君自学习卦术来，第一次起卦这么有感觉过！\r\n　　他一脸欣喜的看着卦像结果。\r\n　　然后……\r\n　　黄山真君面沉如水。\r\n　　黄山真君脸色变臭。\r\n　　且看那卦像：在天愿作比翼鸟，在地愿为连理枝。\r\n　　印象中这诗词是唐朝一个叫白居易诗人写的，很经典，后来经常被人引用来形容爱情？\r\n　　顿时，黄山真君感觉自己整个人都不好了。\r\n　　比翼鸟你妹，连理枝你妹啊！还愿为连理枝，本尊还不如自挂东南枝去啊！\r\n　　难不成他堂堂黄山真君要去和那性别为男的‘书山压力大’演绎一段你死我活、惊天动地的爱情？这不由让他想起了华夏战国时的龙阳君——顿时感觉如吞了蟑螂，倍恶心。\r\n　　“这肯定是本尊卦术修为不够，毕竟才学了一个月……所以本尊应该再算一卦！是的，肯定是这样！”黄山真君再次运转卦术秘法，冥冥中的力量再次翻动《唐诗宋词》。\r\n　　又有一句诗词被抽出。\r\n　　这次卦术秘法运转超级顺畅，黄山真君自我感觉良好，绝对中了！\r\n　　他看向卦像。\r\n　　然后……\r\n　　真君脸色都白了。\r\n　　卦像：“两情若是久长时，又岂在朝朝暮暮!”\r\n　　暮你大爷！\r\n　　“本尊真不信邪了！”黄山真君再次起卦。\r\n　　这次感觉更棒，黄山真君感觉自己的卦像修为在这一刻登峰造极！\r\n　　这次必中！\r\n　　他低头看卦像：“蓦然回首，那人却在，灯火阑珊处。”\r\n　　“……”\r\n　　“深呼吸，深呼吸。”黄山真君淡定合上唐诗宋诗，四十五度角忧郁的望向天空——真是好惆怅的感觉啊！\r\n　　接着，真君淡定的将手中精装版唐诗宋词撕碎，一边撕一边用力点头：“本尊果然没有卦术方面的天赋，天生不是做卦师的料。所以，本尊算出来的卦像肯定都是错误的！”\r\n　　他将撕碎的唐诗宋词扔到一边，心里更是暗暗发誓绝不再手贱算卦！\r\n　　精装诗词的碎片被扔到一边，真君在群中输入道：“那书山压力大……先留着吧。本尊刚才算了一卦，发现他和本尊有缘，会加他入群不是偶然，而是必然！之后会怎样就看他自己的造化吧。”\r\n　　真君用各种卦术方面的词汇搪塞，至于卦像的结果，打死他也绝对不会透露半字！\r\n　　妈蛋，就算有缘，那肯定也是孽缘！\r\n　　“那便留着吧，反正估计不久后他自己也会退群吧。话说真君卦像结果是什么？”北河散人听说过真君在学卦术，所以很好奇这位前辈算出了什么。\r\n　　“……”黄山真君：“那啥，你们继续聊，我有急事先下了。”\r\n　　话罢，他迅速下线，留下一脸茫然的北河散人。\r\n　　————————————————\r\n　　微信搜索［圣骑士的传说］可以加作者的公众号啦！'
        }
      }).obj;
      break;
    }
    case 248:
    {
      all = Mock.mock({
        'obj':{
          'Result': 0,
          'Message': '成功',
          'Data': '\n\t\t\t\t太阳高升，时值正午。\n室友知道宋书航感冒没好，让他好好休息，已经又为他补请了一天病假。\n“病情怎么感觉越来越严重了？是不是因为最近缺少锻炼，身体素质变差了？”宋书航道。\n在他身边有一份皮蛋粥，这是室友中午替他带来的。\n“好人呐！”宋书航毫不犹豫的给室友们发了张好人卡。\n睡了不知多久，他早饿的前胸贴后背，几下扒完了皮蛋粥，又打开电脑。\n习惯性打开聊天软件后，便看到了‘九洲一号群’后代聊天数目的红点。\n宋书航好奇的伸手打开九洲一号群，想看看里面的仙侠资深中二群友们一夜都聊了什么。\n凌晨时的聊天记录浮现在他眼前。\n北河散人关于‘新人’的提问、狂刀三浪的作死，有趣的灵蝶岛前辈。还有自称算了一卦，算出和自己有缘的黄山真君。\n看着聊天记录，几人的形象在书航的脑海中丰满起来。\n“原来是加错人了啊，我就说呢，我都不认识这黄山真君。”\n从聊天记录来看，这群还不是谁都能进的样子？入群都还要有人推荐。\n还有，群里这群资深仙侠迷们的年龄似乎都不小，甚至连女儿都有了。\n而且听口气似乎女儿都不小了？那算起来说不定都四五十岁人了，这么大了还中二，他们的女儿还真辛苦。\n刷着群里的聊天记录，宋书航保持着潜水状态，绝对不发言。\n看群员们犯二是很有意思的事情，但如果自己也掺进去的话那算啥？自己又不犯二。\n所以他的打算就是潜水看聊天记录，纯当每日笑话。\n等到哪一天，他感觉这群没意思了，就会退出九洲一号群。\n他自己一直是这么认为的。\n＊＊＊＊＊＊＊＊＊＊\n不知不觉，十天时间过去……\n６月１日，周六，儿童节。\n书航的室友都是半住宿半走读的，也就是周一至周五都住宿，周末会回家。所以一到周末，宿舍就只剩他一人孤零零的。\n宋书航的感冒早恢复，就是还有点鼻塞和咳嗽。这咳嗽是寒咳，恢复起来比较麻烦。保养不好的话会咳上个把月。\n周六休息，书航一觉睡到八点才起床，又去食堂吃了点清淡的。\n无事可作便回到宿舍。\n打开电脑后，他习惯性的到九洲一号群看聊天记录，这已经成了他每天打发时间的好方法。\n不知不觉，加入这个群已经十多天。\n潜水中的十多天时，看到群里人大部分都在聊着到哪个秘境闯荡，收获多少。又或者哪里出现恶鬼妖魔，要么降伏，要么斩杀。\n讲的都跟真的似的。宋书航想，自己要是将这些内容复制下来，再修饰一下都能发到网上当仙侠小说赚稿费了。\n十天时间内，宋书航也认识了群里好几个人物。\n比如很少冒头的群主黄山真君。\n还有从他加群后就没出现过的两位管理员大罗教雨月真君、七修尊者。\n经常在线的‘情报通’北河散人、作的一手好死的狂刀三浪、张口闭口就是打架的苏氏阿七，惜字如金的药师。\n还有一直潜水，就算冒头也只发表情和标点符号的云游僧通玄。据说这位高僧在修闭口禅，不仅不能说话，连打字都不行，最多就发个表情。\n最后，就是在这稍稍有点中二病群里，发言却很正常的灵蝶岛羽柔子。她的号码和宋书航的只差一个数字。托她的福，书航才有机会进入这个九洲一号群呢。\n这些情报都是热情的‘北河散人’向‘灵蝶岛羽柔子’介绍其他群成员得到的。\n……\n……\n今天打开九洲一号群，第一眼便看到药师的发言。\n难得，惜字如金的药师开金口：“改良了个基础丹方。”\n这可是加标点有七个字的一句话，宋书航加群到现在都没看药师发过这么长的消息。所以，他很好奇的看了下去。\n药师的消息是凌晨时发的。\n“简化版淬体液丹方：人参三两、枸杞子四两三钱；朝露玄草一两；阳起石三两、女儿香一两三钱……鲜霸王枝一两、九阳赤炎竹切片四两……”\n一连串四十五种药材，其中有比较眼熟的人参、枸杞之类，也有比较生僻的阳起石之流，还有一些根本没听过的什么朝露玄草、鲜霸王枝、九阳赤炎竹之类。\n“按配方比例逐次投入药炉，闷烧约五分钟；投入新药材，继续闷烧约五分钟。注意火候！如此循环，直至药液成糊。成品淬体液色泽为黑，透明，味冲。”\n通俗易懂！\n四十多个药名书航认得不多，他好奇的在网上查了一下。\n丹方中，有三十种是普通的中医药材，都是补气血之类的。\n还有十五种如朝露玄草、霸王枝啊、赤炎竹啊则根本没听过，不会是这位‘药师’和群里的人妄想出来的东西吧？\n“这些家伙病太深了，连药方都搞出来了，不会真有人按药方去做，然后吃下那药糊吧？”宋书航心中暗道。\n他有些担心，因为饭可以乱吃，药却不能乱喝啊！\n乱吃药会死人的吧？要不要劝一下这些中二的群友？怎么说自己都在边上看了十多天呢。\n要是群里有人乱吃药死掉的话，他有点于心不忍。\n他继续下接聊天记录，果然，已经有人按丹方炼药去了！\n竟然是群里显的最正常的灵蝶岛羽柔子这姑娘，时间在凌晨两点左右。\n灵蝶岛羽柔子：“和老版淬体液比起来少了很多已经稀有的药材，炼药过程也简化了太多。药师前辈，火候要掌握到什么程度？我刚试了一下结果中途就失败了。还有药效的话和过去的比起来差距多少？”\n“效２：１。”药师道。\n药效只有以前的一半，毕竟减少了很多珍贵的药材。但是以这么普通大众化的药材就能配出淬体液，怎么说都赚了。\n“火候和具体闷烧时间自己摸索，解释不了。”药师再次难得的发了句长话，也只有在关于炼丹药的问题上，他才能咬牙多打几个字：“还有，如果妳的‘控火诀’不好，推荐使用控火法宝。”\n“谢谢前辈，我再去试试。”灵蝶岛羽柔子发了个笑脸，便潜水去了。\n灵蝶岛羽柔子最后发言是凌晨两点十三分，如果她后面就去炼丹了的话，算算时间她应该已经炼了好几炉丹药了？\n会死人的吧？本来就是一群中二病很萌萌达了，再吃错药的话，岂不是会变的超级萌萌哒？原本说不定还能再抢救一下，现在吃了药后就根本没救了好不好！\n他终于良心过不去，忍不住在聊天框中输入：“药不能乱吃啊！”\n正当他准备敲回车，输入自己在群里的第一句话时……聊天窗口震动了一下。\n群聊天画面中弹出了个大笑脸。\n却是从宋书航入群来就没冒头过的管理员七修尊者：“配方很不错，我刚同时试了七炉，很轻松就全成功了，成功率是极高。我服用了一些，药效差不多有老款淬体液的二分之一效果还多一点。但配方成本却比老版的降低了十倍。虽然只是最低阶的淬体液，但如今天地灵气日渐稀薄，珍贵药材越加稀少的我们来说，真是个好东西。药师，继续努力。若是能改善三品以上的丹方，那就真是功德无量了。”\n“补充：最重要的是，炼制方法难度大大降低，甚至可以交给练药学徒炼制。”\n七修尊者乃是群里有名的大前辈，实力比黄山真君还要强上一线。而且他在炼丹方面也有极深的造诣，在这个群里可以说是炼丹方面的权威，他的赞扬自然让药师这个后辈倍受鼓舞。\n“谢前辈，我努力！”药师激动的打出了六字以上的一句话，而且速度还很快。\n宋书航嘴角都开始抽搐起来：竟然已经有人炼制服用那‘淬体液’了？\n;',
        }
      }).obj;
      break;
    }
    }
    return {
      status: 200,
      data: all,
    };
  },
  '/api/v1/books/{bookId}/chapterList': ({ method, url, params, urlparams, headers }) => {
    const urlx = params.chapterId;
    const all = Mock.mock({
      'list':[
        {
          'id':1,
          'title':'第一章',
          'chapterId':247,
        },{
          'id':2,
          'title':'第二章',
          'chapterId':248,
        },{
          'id':3,
          'title':'第三章',
          'chapterId':247,
        },
        {
          'id':4,
          'title':'第四章',
          'chapterId':248,
        }
      ]
    }).list;
    return {
      status: 200,
      data: all,
    };
  },
};
